address: 'https://test-stand.gb.ru/login'
address2: 'https://test-stand.gb.ru/posts/create'
url: 'https://test-stand.gb.ru/gateway/login'
url1: 'https://test-stand.gb.ru/api/posts/'
username: 'maiaa563'
password: '802b4c7b2d'
driver_path: chromedriver.exe
browser: chrome
sleep_time: 1
